resources:
  pipelines:
    # =========================================================
    # 1. Bronze Layer Pipeline
    # =========================================================
    soccer_bronze_pipeline:
      name: "Soccer Data - Bronze Layer (${bundle.target})"
      catalog: "soccer_data"
      target: "extract"
      serverless: true
      libraries:
        - file:
            path: ../club-soccer-data/bronze-layer/player_match_bronze.sql
        - file:
            path: ../club-soccer-data/bronze-layer/team_match_level.sql
      
      configuration:
        soccer.datastore.extract: abfss://extract@soccerdatastore.dfs.core.windows.net/

    # =========================================================
    # 2. Silver Layer Pipeline
    # =========================================================
    soccer_silver_pipeline:
      name: "Soccer Data - Silver Layer (${bundle.target})"
      catalog: "soccer_data"
      target: "processed"
      serverless: true
      libraries:
        # List all your Silver transformation scripts
        - file:
            path: ../club-soccer-data/silver-layer/results.py

    # =========================================================
    # 3. Gold Layer Pipeline
    # =========================================================
    soccer_gold_pipeline:
      name: "Soccer Data - Gold Layer (${bundle.target})"
      catalog: "soccer_data"
      target: "analyze"
      serverless: true
      libraries:
        # List all your Gold aggregation scripts
        - file:
            path: ../club-soccer-data/gold-layer/headline_form_table.py
        - file:
            path: ../club-soccer-data/gold-layer/trendline_tables.py
