resources:
  pipelines:
    # =========================================================
    # 1. Bronze Layer Pipeline
    # =========================================================
    soccer_bronze_pipeline:
      name: "Soccer Data - Bronze Layer"
      target: "soccer_data_bronze"
      libraries:
        # Add as many scripts as you need here using a hyphen (-)
        - notebook:
            path: ../club-soccer-data/bronze-layer/player_match_bronze.sql
        - notebook:
            path: ../club-soccer-data/bronze-layer/team_match_level.sql
      
      configuration:
        soccer.datastore.extract: /mnt/soccerdatastore/extract
      clusters:
        - label: "default"
          num_workers: 1

    # =========================================================
    # 2. Silver Layer Pipeline
    # =========================================================
    soccer_silver_pipeline:
      name: "Soccer Data - Silver Layer"
      target: "soccer_data_silver"
      libraries:
        # List all your Silver transformation scripts
        - notebook:
            path: ../club-soccer-data/silver-layer/results.py

    # =========================================================
    # 3. Gold Layer Pipeline
    # =========================================================
    soccer_gold_pipeline:
      name: "Soccer Data - Gold Layer"
      target: "soccer_data_gold"
      libraries:
        # List all your Gold aggregation scripts
        - notebook:
            path: ../club-soccer-data/gold-layer/headline_form_table.py
